### ISSUE TITLE
Organisation logo when link is organisation colour

### ISSUE THREAD

**Issue by injms** [alphagov/government-frontend#1487] opened 2019-09-16 13:08 UTC
When an organisation logo has a link around it, it is displayed using the department colours when focused and unfocused:

<img width="257" alt="Screen Shot 2019-09-16 at 14 05 49" src="https://user-images.githubusercontent.com/1732331/64960408-24be0f00-d88b-11e9-97d2-cdfaba4256f4.png">
<img width="224" alt="Screen Shot 2019-09-16 at 14 05 32" src="https://user-images.githubusercontent.com/1732331/64960419-27b8ff80-d88b-11e9-9a85-b029f10fde27.png">

Example taken from the [About page for DCMS](https://www.gov.uk/government/organisations/department-for-digital-culture-media-sport/about)

The expected behaviour in both cases is for the text to be black.

**Comment by andysellick** [comment] 2019-09-18 08:11
@injms dang it, I thought this would be fixed by https://github.com/alphagov/govuk_publishing_components/pull/1088, I'll take another look.

**Comment by andysellick** [comment] 2019-09-18 08:37
This is a wider problem than just the logo - it happens on almost every link on this page (although not all of them, oddly). It's caused by an overriding nested class to set the link colour, which also happens on other organisation pages. We need to address this as the root cause of the problem.

Most of the components used on these pages have a branding option, but it's not going to be a small piece of work - we need to check they're all turned on, add it for those that don't have it, then remove all the page override classes.

**Comment by owenatgov** [comment] 2021-11-11 12:29
Made redundant by https://github.com/alphagov/government-frontend/pull/2129 Closing!

**Closed by owenatgov** 2021-11-11 12:29 UTC
